# Site
title: Welcome to wisper
subtitle: wispeeer wisper
description: 'Generate by Wispeeer<br> <a href="https://github.com/Wispeeer/wispeeer">wispeeer</a>.'
keywords: IT, CS
author: Mardan M
language: en
timezone: Asia/Shanghai

# Urls
root: 
permalink: website

# Directory
source_dir: source
public_dir: public
article_dir: post

# Pagination
per_page: 9
pagination_dir: articles

## Themes
theme: wisper

# Deployment
deploy:
  type: 'git'
  repo: 
  branch: master